# Form implementation generated from reading ui file 'ui/wx_parameter.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(441, 33)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_enabled = QtWidgets.QCheckBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_enabled.sizePolicy().hasHeightForWidth())
        self.cb_enabled.setSizePolicy(sizePolicy)
        self.cb_enabled.setText("")
        self.cb_enabled.setChecked(True)
        self.cb_enabled.setObjectName("cb_enabled")
        self.horizontalLayout.addWidget(self.cb_enabled)
        self.lb_symbol = QtWidgets.QLabel(parent=Form)
        self.lb_symbol.setObjectName("lb_symbol")
        self.horizontalLayout.addWidget(self.lb_symbol)
        self.lb_name = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_name.sizePolicy().hasHeightForWidth())
        self.lb_name.setSizePolicy(sizePolicy)
        self.lb_name.setObjectName("lb_name")
        self.horizontalLayout.addWidget(self.lb_name)
        self.dsb_value = QtWidgets.QDoubleSpinBox(parent=Form)
        self.dsb_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsb_value.setDecimals(6)
        self.dsb_value.setMinimum(1e-06)
        self.dsb_value.setMaximum(0.5)
        self.dsb_value.setSingleStep(0.001)
        self.dsb_value.setProperty("value", 0.5)
        self.dsb_value.setObjectName("dsb_value")
        self.horizontalLayout.addWidget(self.dsb_value)
        self.lb_unit = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_unit.sizePolicy().hasHeightForWidth())
        self.lb_unit.setSizePolicy(sizePolicy)
        self.lb_unit.setObjectName("lb_unit")
        self.horizontalLayout.addWidget(self.lb_unit)
        self.lb_symbol.setBuddy(self.dsb_value)
        self.lb_name.setBuddy(self.dsb_value)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_symbol.setText(_translate("Form", "X"))
        self.lb_name.setText(_translate("Form", "name"))
        self.lb_unit.setText(_translate("Form", "unit"))
